
git add .codecatalyst/workflows/docker-build-push.yaml
git commit -m "Add CodeCatalyst workflow"
git pushname: Docker Build and Push to ECR

triggers:
  - type: push
    branches:
      - main

actions:
  build-and-push:
    identifier: aws/build@v1.0.0
    inputs:
      sources:
        - workflowSource
    configuration:
      runtime: docker
      commands:
        - echo "Logging in to ECR..."
        - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 095312288238.dkr.ecr.us-east-1.amazonaws.com
        - echo "Building Docker image..."
        - docker build --platform=linux/amd64 -t washingindexskill:latest .
        - docker tag washingindexskill:latest 095312288238.dkr.ecr.us-east-1.amazonaws.com/washingindexskill:latest
        - echo "Pushing Docker image to ECR..."
        - docker push 095312288238.dkr.ecr.us-east-1.amazonaws.com/washingindexskill:latest
